#Equilateral Triangle
import turtle
pen=turtle.Turtle()
screen=turtle.Screen()
screen.bgcolor("lavender")
pen.fillcolor("hotpink")
pen.shape("turtle")
pen.begin_fill()
pen.forward(150)
pen.left(120)
pen.forward(150)
pen.left(120)
pen.forward(150)
pen.end_fill()


#Rectangle
pen.penup()
pen.goto(-80, -45) 
pen.pendown()
pen.fillcolor("lightgreen")
pen.begin_fill()
pen.forward(175)
pen.left(90)
pen.forward(125)
pen.left(90)
pen.forward(175)
pen.left(90)
pen.forward(125)
pen.end_fill()

#Hexagon
pen.penup()
pen.goto(-150, 150)
pen.pendown()
pen.fillcolor("darkblue")
pen.begin_fill()
pen.forward(90)
pen.left(60)
pen.forward(90)
pen.left(60)
pen.forward(90)
pen.left(60)
pen.forward(90)
pen.left(60)
pen.forward(90)
pen.left(60)
pen.forward(90)
pen.left(60)
pen.end_fill()

screen.mainloop()