import turtle
pen = turtle.Turtle()
screen=turtle.Screen()
screen.bgcolor("skyblue")
pen.fillcolor("Pink")
pen.begin_fill()
pen.forward(300)
pen.right(90)
pen.forward(100)
pen.right(90)
pen.forward(300)
pen.right(90)
pen.forward(100)
pen.end_fill()

screen.mainloop()
